-
  id: 1-1-1
  message: Gift card giveaway  ğŸ   winners have been ğŸ“¢ / ğŸ‘€ for new tasks on Friday, Mar 4th! ğŸ—“
  start_at: 2022-02-28
  end_at: 2022-03-03
-
  id: 1-2-1
  message: New studies ğŸ§   are now available! Happy learning!ğŸ¤“
  start_at: 2022-03-04
  end_at: 2022-03-10
-
  id: 1-2-2
  message: Keep a good thing going - complete available studies â˜‘ï¸ by Monday, Mar 21st to enter a gift card ğŸ  giveaway!
  start_at: 2022-03-11
  end_at: 2022-03-13
-
  id: 1-2-3
  message: New gift card ğŸ giveaways will be awarded on March 25th, and new tasks will be available on Tuesday, Mar 28th! ğŸ—“
  start_at: 2022-03-14
  end_at: 2022-03-24
-
  id: 1-2-4
  message: Gift card giveaway winners ğŸ  have been chosen! ğŸ‘€ for new tasks on Tuesday, Mar 28th!
  start_at: 2022-03-25
  end_at: 2022-03-27
-
  id: 1-3-1
  message: A month of learning beckons - access our all new studies! ğŸ‘“
  start_at: 2022-03-28
  end_at: 2022-04-03
-
  id: 1-3-2
  message: Lucky you - studies ğŸ“š are still available to enter an exciting gift card giveaway!ğŸ
  start_at: 2022-04-04
  end_at: 2022-04-12
-
  id: 1-3-3
  message: Gift card giveaways ğŸ“¢ on Friday, Apr 22nd! ğŸ¥³
  start_at: 2022-04-13
  end_at: 2022-04-21
-
  id: 1-3-4
  message: Gift card ğŸ giveaway winners have been chosen! Continue exploring - the rewards ğŸ† haven't ended yet!
  start_at: 2022-04-22
  end_at: 2022-04-24
-
  id: 1-3-5
  message: Last chance â³ to complete all studies by Apr 29 for a chance to win a pair of Apple AirPods! ğŸ§
  start_at: 2022-04-25
  end_at: 2022-04-29
