-
  id: 1-1-1
  message: â˜• Starbucks gift card giveaways ğŸ  ğŸ“¢ on Friday, Feb 25th! / ğŸ‘€ for new tasks on Monday, Feb 28th!
  start_at: 2022-02-21
  end_at: 2022-02-24
-
  id: 1-1-2
  message: Starbucks â˜• gift card giveaway winners have been chosen! New studies ğŸ§  coming in on Monday, Feb 28th! ğŸ—“
  start_at: 2022-02-25
  end_at: 2022-02-27
-
  id: 1-1-3
  message: New tasks are now available! Happy learning!ğŸ¤“
  start_at: 2022-02-28
  end_at: 2022-03-06
-
  id: 1-2-1
  message: Keep a good thing going - complete available studies by to enter an Amazon gift card ğŸ  giveaway!
  start_at: 2022-03-07
  end_at: 2022-03-13
-
  id: 1-2-2
  message: Amazon gift card ğŸ giveaways will be awarded on March 21st, and new tasks will be available on Tuesday, Mar 22nd! ğŸ—“
  start_at: 2022-03-14
  end_at: 2022-03-20
-
  id: 1-2-3
  message: Amazon gift card giveaway winners ğŸ  have been chosen!  ğŸ‘€ for new tasks on Tuesday, Mar 22nd!
  start_at: 2022-03-21
  end_at: 2022-03-21
-
  id: 1-3-1
  message: A month of learning beckons - access our all new studies! ğŸ‘“
  start_at: 2022-03-22
  end_at: 2022-03-28
-
  id: 1-3-2
  message: Lucky you - studies ğŸ“š are still available to enter a Nike gift card giveaway!
  start_at: 2022-03-29
  end_at: 2022-04-06
-
  id: 1-3-3
  message: Nike âœ” gift card giveaways ğŸ“¢ on Friday, Apr 15th! ğŸ¥³
  start_at: 2022-04-07
  end_at: 2022-04-14
-
  id: 1-3-4
  message: Nike gift card giveaway winners have been chosen! Continue exploring - the rewards ğŸ† haven't ended yet!
  start_at: 2022-04-15
  end_at: 2022-04-17
-
  id: 1-3-5
  message: Last chance â³ to complete all studies by Apr 19 for a chance to win a pair of Apple AirPods! ğŸ§
  start_at: 2022-04-18
  end_at: 2022-04-19
